fix: update some build config option
1. update webpack version to fix config validate error

ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.output.environment has an unknown property 'asyncFunction'

2. disable prebundle to fix webpack error

EnvironmentNotSupportAsyncWarning: The generated code contains 'async/await' because this module is using "external script".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors

3. change h5 output related options to fix webpack output-filename-format error

[DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)